### ISSUE TITLE
Visible image compression artifacts

### ISSUE THREAD

**Issue by Sonoid** [ianmartinez/AtlinUtils#9]
When an image is set through Chameleon, there is a visible compression to any of the images (artifacts/ lowering of quality). it's nothing extreme, but when I set the background manually there is a noticeable rise in quality. I'm assuming this is because chameleon actually uploads the images to itself at a slightly lower quality than full.  Is there a way to stop chameleon from compressing images?

**Comment by ianmartinez** [comment]
I'm not sure why it would be doing that. I'll look into it.

Since I now have a lot of extra free time, I'm going through my projects one by one and spending about a week or two overhauling each one.

I started a [massive refactor](https://github.com/ianmartinez/LangPad/blob/master/Changelog.txt) on [my largest and oldest project](https://github.com/ianmartinez/LangPad) this week, which is almost complete. After I work on another project, [ASCII Studio](https://github.com/ianmartinez/ASCII-Studio), I'm planning on improving Chameleon, so I will look into this issue and get back to you when I'm developing version 2.0 in the coming weeks.

**Comment by Sonoid** [comment]
Awesome! Thank you!

**Comment by ianmartinez** [comment]
I looked into it and the way it worked before was that it loading the image into a picture box and then saving it when you imported an image and now it just copies the image over directly with no processing, so there shouldn't be compression anymore.

Can you test the [fix here](https://github.com/ianmartinez/Chameleon/blob/master/Chameleon/ChameleonRelease.exe) and see if it fixes your issue?

**Comment by Sonoid** [comment]
It seems to be working great! Thank you. Though one more thing that I had thought of, could you possibly make it run on startup?

**Comment by ianmartinez** [comment]
You can have it run directly by passing it the “-a” argument:
`Chameleon.exe -a`

Just place a shortcut to Chameleon with that parameter in the startup folder and it will start running at startup.

For version 2.0, which I’m working on, the installer will automatically do this for you, but “-a” parameter trick works in the current version for now.
